### ISSUE TITLE
Proposal: additional attributes for generated commands

### ISSUE THREAD

**Issue by jubba2001** [DevExpress/DevExpress.Mvvm.CodeGenerators#14]
Please, add the possibility to copy additional attributes from methods to generated commands, as it is done for generated properties:
```[GenerateViewModel]
partial class ViewModel {

    [GenerateProperty]
    [StringLength(100, MinimumLength = 5)]
    string username;

    [GenerateCommand]
    [Display(GroupName = "<Commands>-", Name = "New...")]
    void AddNew()
    {
        //...
    }
}
```
Adding attributes to generated ``DelegateCommands``, allows programmers to create attribute-based logic on commands.  By example, to customise displaying of commands in the view.

**Comment by BelousovSer** [comment]
Hello,
Thank you so much for your suggestion. It indeed makes sense. We will add this functionality in the next release.
