### ISSUE TITLE
Enhancement: Microsoft.Toolkit.Mvvm Support

### ISSUE THREAD

**Issue by omeryanar** [DevExpress/DevExpress.Mvvm.CodeGenerators#16]
Since [MVVM Light Toolkit](https://github.com/lbugnion/mvvmlight#mvvm-light-toolkit) is not maintained anymore and it recommends [Microsoft.Toolkit.Mvvm](https://docs.microsoft.com/en-us/windows/communitytoolkit/mvvm/introduction), can you add support for it?
It includes additional command classes such as [AsyncRelayCommand](https://docs.microsoft.com/en-us/windows/communitytoolkit/mvvm/asyncrelaycommand).

**Comment by BelousovSer** [comment]
When we started our development of Code Generators, we supported the frameworks that were the most popular among users. This is why, we mostly focused on the PRISM and MVVM Light support. We did not make a final decision about the Microsoft.Toolkit.MVVM, but we will take your inquiry into account in the future. Thank you for your feedback.



Please note that it's possible to execute commands asynchronously in MVVM Light as well. Please refer to the following code for more information:
```cs       
        [GenerateCommand]
        public Task WithNoArg() => Task.CompletedTask;
        [GenerateCommand]
        public Task WithArg(int arg) => Task.CompletedTask;
```
        
Generated code:

```cs
        RelayCommand? withNoArgCommand;
        public RelayCommand WithNoArgCommand => withNoArgCommand ??= new RelayCommand(async () => await WithNoArg(), null);
        RelayCommand<int>? withArgCommand;
        public RelayCommand<int> WithArgCommand => withArgCommand ??= new RelayCommand<int>(async (arg) => await WithArg(arg), null);
```
