### ISSUE TITLE
ChangedNotification for calculated properties

### ISSUE THREAD

**Issue by D0ctorWh0** [DevExpress/DevExpress.Mvvm.CodeGenerators#2]
Would be great to generate change notifications for calculated properties. For example for class 

```
[GenerateViewModel]
public partial class Model
{
    [GenerateProperty]
    public int _x;
    [GenerateProperty]
    public int _y;
    public int Z => _x * _y;
}
```

would be great to have X and Y generated properties have not only 

`RaisePropertyChanged(XChangedEventArgs);`

but also 

`RaisePropertyChanged(ZChangedEventArgs);`

**Comment by Faramoz161** [comment]
Hello,

Although our view model code generator doesn't support automatic notification for dependent properties, you can achieve your goal using the On[PropertyName]Changed and On[PropertyName]Changing methods in the following manner:


```
void OnXChanged() => RaisePropertyChanged(ZChangedEventArgs);
void OnYChanged() => RaisePropertyChanged(ZChangedEventArgs);

// or

[GenerateProperty(OnChangedMethod = nameof(NotifyZ))]
int _x, _y;
void NotifyZ() => RaisePropertyChanged(ZChangedEventArgs);
```


Please refer to the following help topic for additional information: [Property Change Notifications](https://docs.devexpress.com/WPF/402989/mvvm-framework/viewmodels/compile-time-generated-viewmodels#property-change-notifications)
