### ISSUE TITLE
VS2022 support

### ISSUE THREAD

**Issue by impoetk** [DevExpress/DevExpress.Mvvm.CodeGenerators#7]
Code does not generate under vs2022 preview 3

**Comment by Faramoz161** [comment]
Hello,

Please check the CodeGenerator and language version you are using. In VS 2022, CodeGenerator v21.1.0 requires C# 10. However, v21.1.1 supports C# 9 in VS 2022. So, it's likely that you need to update CodeGenerator or language version.

If this doesn't help, please clarify the following points:

1. What project type are you using (WPF, WinForms, Console Application)?
2. What is the project's framework version?
3. What is the project's language version?

**Comment by impoetk** [comment]
I opened my project in vs2022 to check the settings i have, and now the generating works

my setup is WPF application, NET 5 (current) and language version not set in the .csproj

Thanks, im closing the issue
