### ISSUE TITLE
sealed class generates protected method

### ISSUE THREAD

**Issue by impoetk** [DevExpress/DevExpress.Mvvm.CodeGenerators#8]
When decorating a sealed class with GenerateViewModel, the raise property changed method is generated with "protected" modifier, which generates the following warning:

Warning	CS0628	'MainWindowVm.RaisePropertyChanged(PropertyChangedEventArgs)': new protected member declared in sealed type

**Comment by Faramoz161** [comment]
Thank you for informing us of this issue. We will fix it as soon as we can.

**Comment by BelousovSer** [comment]
We fixed this issue in v21.1.3. An updated NuGet package is available for download.
